### ISSUE TITLE
[Question] How do I apply this as a font for everything in Minecraft?

### ISSUE THREAD

**Issue by ConqAra** [Darkhax-Minecraft/Nyctography#1]
### Question

I tried looking stuff up and applying it as maybe a resourcepack, but nothing worked. Is it done differently? I went to the language tab too in the game to see maybe if the mod added something there. I wanted to make the whole game's font Nyctography using this but I'm unsure how to do it?

**Comment by Darkhax** [comment]
Hello, 

Yes, it is possible to change the default font using a resource pack. This can be done by overriding the contents of the `default.json` file with the contents of the [mods font file](https://github.com/Darkhax-Minecraft/Nyctography/blob/1.21.1/common/src/main/resources/assets/nyctography/font/nyctography.json). I've made this example resource pack which seems to work pretty well. 

[Nyctography-Default-1.0.0-1.21.1.zip](https://github.com/user-attachments/files/17952883/Nyctography-Default-1.0.0-1.21.1.zip)

**Comment by ConqAra** [comment]
Thank you!
